server:
  port: 8080

spring:
  application:
    name: optiroute-backend
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/optiroute?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always  # changed - > creates tables first after starting of container
  jpa:
    defer-datasource-initialization: true  # changed to avoid memory leakage
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: ${JWT_SECRET:9a4f2c8d3b7a1e6f4g5h8i0j2k4l6m8n0p2q4r6s8t0v2x4z6}
  expiration: 86400000 # 1 day in ms
